In [17]:
import pandas as pd 
import numpy as np

In [18]:
df = pd.read_csv('Walmart.csv',encoding_errors = 'ignore')

In [19]:
df.head(10)

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48
5,6,WALM026,Denton,Electronic accessories,$85.39,7.0,25/03/19,18:30:00,Ewallet,4.1,0.48
6,7,WALM088,Cleburne,Electronic accessories,$68.84,6.0,25/02/19,14:36:00,Ewallet,5.8,0.33
7,8,WALM100,Canyon,Home and lifestyle,$73.56,10.0,24/02/19,11:38:00,Ewallet,8.0,0.18
8,9,WALM066,Grapevine,Health and beauty,$36.26,2.0,10/01/19,17:15:00,Credit card,7.2,0.33
9,10,WALM065,Texas City,Food and beverages,$54.84,3.0,20/02/19,13:27:00,Credit card,5.9,0.33

In [20]:
df.shape

(10051, 11)

In [21]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

In [23]:
# All Duplicates
df.duplicated().sum()

np.int64(51)

In [24]:
# Remove duplicates
df.drop_duplicates(inplace = True)
df.duplicated().sum()

np.int64(0)

In [25]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [26]:
# Dropping all rows withn missing records 
df.dropna(inplace = True)
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   object
 2   City            9969 non-null   object
 3   category        9969 non-null   object
 4   unit_price      9969 non-null   object
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   object
 7   time            9969 non-null   object
 8   payment_method  9969 non-null   object
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(3), int64(1), object(7)
memory usage: 934.6+ KB

In [28]:
# change data type of Unit price 
df['unit_price'] = df['unit_price'].str.replace('$','').astype(float)

In [29]:
df.columns.tolist()

['invoice_id',
 'Branch',
 'City',
 'category',
 'unit_price',
 'quantity',
 'date',
 'time',
 'payment_method',
 'rating',
 'profit_margin']

In [30]:
for i in df.columns:
    print(i)

invoice_id
Branch
City
category
unit_price
quantity
date
time
payment_method
rating
profit_margin

In [31]:
df['total'] = df['unit_price'] * df['quantity']
df['total']

0       522.83
1        76.40
2       324.31
3       465.76
4       604.17
         ...
9995    111.00
9996    116.00
9997    156.00
9998    158.00
9999    186.00
Name: total, Length: 9969, dtype: float64

In [37]:
# Get all table name in the lower case 
df.columns= df.columns.str.lower()

In [38]:
df.columns

Index(['invoice_id', 'branch', 'city', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin', 'total'],
      dtype='object')

In [39]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "postgres"
password = "pathakanshu8055"
host = "localhost"
port = "5432"
database = "Walmart Sales Analysis"

engine = create_engine(f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}')
table_name = 'walmart'

df.to_sql(table_name , engine , if_exists = 'replace', index = False)
print(table_name, database)

walmart Walmart Sales Analysis